auth:
  ego:
    clientId: pensato
    clientSecret: pensatotest
    introspectionUri: https://localhost:9001/api/o/check_api_key
    userInfoUri: https://localhost:9001/api/users
    scopes:
      - DACO.READ
      - WG.WRITE